import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "KIS-POINTS",
  description: "Generated by KIS-POINTS",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* THE GLOBAL GOD BOX */}
      {/* We keep 'antialiased' for font smoothing, and add our rigid workstation walls */}
      <body className="antialiased flex flex-col h-[100dvh] w-screen overflow-hidden bg-slate-50">
        {children}
      </body>
    </html>
  );
}