import type { Metadata, Viewport } from "next";
import { LandingLayout } from "@/layouts/landing/LandingLayout";

export const metadata: Metadata = {
  title: "KIS-POINTS",
  description: "Generated by KIS-POINTS",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <LandingLayout>{children}</LandingLayout>;
}
